"""baseline schema

Revision ID: 267725fe7017
Revises: 
Create Date: 2026-04-30 16:54:10.117775

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '267725fe7017'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('analysis_sessions', schema=None) as batch_op:
        batch_op.alter_column('current_step',
               existing_type=postgresql.ENUM('PROPERTY_FACTS', 'COMPARABLE_SEARCH', 'COMPARABLE_REVIEW', 'WEIGHTED_SCORING', 'VALUATION_MODELS', 'REPORT_GENERATION', name='workflow_step'),
               type_=sa.Enum('PROPERTY_FACTS', 'COMPARABLE_SEARCH', 'COMPARABLE_REVIEW', 'WEIGHTED_SCORING', 'VALUATION_MODELS', 'REPORT_GENERATION', name='workflowstep'),
               existing_nullable=False,
               existing_server_default=sa.text("'PROPERTY_FACTS'::workflow_step"))
        batch_op.drop_constraint(batch_op.f('analysis_sessions_session_id_key'), type_='unique')
        batch_op.drop_index(batch_op.f('idx_analysis_sessions_session_id'))
        batch_op.drop_index(batch_op.f('idx_analysis_sessions_user_id'))
        batch_op.create_index(batch_op.f('ix_analysis_sessions_session_id'), ['session_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_analysis_sessions_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('buy_hold_scenarios', schema=None) as batch_op:
        batch_op.alter_column('market_rent',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Float(),
               existing_nullable=False)
        batch_op.alter_column('capital_structures',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=False)
        batch_op.alter_column('price_points',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=False)

    with op.batch_alter_table('comparable_sales', schema=None) as batch_op:
        batch_op.alter_column('sale_price',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               type_=sa.Float(),
               existing_nullable=False)
        batch_op.alter_column('property_type',
               existing_type=postgresql.ENUM('single_family', 'multi_family', 'commercial', name='property_type'),
               type_=sa.Enum('SINGLE_FAMILY', 'MULTI_FAMILY', 'COMMERCIAL', name='propertytype'),
               existing_nullable=False)
        batch_op.alter_column('bathrooms',
               existing_type=sa.NUMERIC(precision=3, scale=1),
               type_=sa.Float(),
               existing_nullable=False)
        batch_op.alter_column('construction_type',
               existing_type=postgresql.ENUM('frame', 'brick', 'masonry', name='construction_type'),
               type_=sa.Enum('FRAME', 'BRICK', 'MASONRY', name='constructiontype'),
               existing_nullable=False)
        batch_op.alter_column('interior_condition',
               existing_type=postgresql.ENUM('needs_gut', 'poor', 'average', 'new_reno', 'high_end', name='interior_condition'),
               type_=sa.Enum('NEEDS_GUT', 'POOR', 'AVERAGE', 'NEW_RENO', 'HIGH_END', name='interiorcondition'),
               existing_nullable=False)
        batch_op.alter_column('distance_miles',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               type_=sa.Float(),
               existing_nullable=False)
        batch_op.alter_column('latitude',
               existing_type=sa.NUMERIC(precision=10, scale=8),
               type_=sa.Float(),
               existing_nullable=True)
        batch_op.alter_column('longitude',
               existing_type=sa.NUMERIC(precision=11, scale=8),
               type_=sa.Float(),
               existing_nullable=True)
        batch_op.drop_index(batch_op.f('idx_comparable_sales_address'))
        batch_op.drop_index(batch_op.f('idx_comparable_sales_session_id'))
        batch_op.create_index(batch_op.f('ix_comparable_sales_address'), ['address'], unique=False)
        batch_op.create_index(batch_op.f('ix_comparable_sales_session_id'), ['session_id'], unique=False)

    with op.batch_alter_table('comparable_valuations', schema=None) as batch_op:
        batch_op.alter_column('price_per_sqft',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Float(),
               existing_nullable=False)
        batch_op.alter_column('price_per_unit',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               type_=sa.Float(),
               existing_nullable=False)
        batch_op.alter_column('price_per_bedroom',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               type_=sa.Float(),
               existing_nullable=False)
        batch_op.alter_column('adjusted_value',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               type_=sa.Float(),
               existing_nullable=False)
        batch_op.alter_column('adjustments',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
        batch_op.drop_index(batch_op.f('idx_comparable_valuations_valuation_result_id'))
        batch_op.create_index(batch_op.f('ix_comparable_valuations_valuation_result_id'), ['valuation_result_id'], unique=False)

    with op.batch_alter_table('fix_flip_scenarios', schema=None) as batch_op:
        batch_op.alter_column('acquisition_cost',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               type_=sa.Float(),
               existing_nullable=False)
        batch_op.alter_column('renovation_cost',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               type_=sa.Float(),
               existing_nullable=False)
        batch_op.alter_column('holding_costs',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               type_=sa.Float(),
               existing_nullable=False)
        batch_op.alter_column('financing_costs',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               type_=sa.Float(),
               existing_nullable=False)
        batch_op.alter_column('closing_costs',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               type_=sa.Float(),
               existing_nullable=False)
        batch_op.alter_column('total_cost',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               type_=sa.Float(),
               existing_nullable=False)
        batch_op.alter_column('exit_value',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               type_=sa.Float(),
               existing_nullable=False)
        batch_op.alter_column('net_profit',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               type_=sa.Float(),
               existing_nullable=False)
        batch_op.alter_column('roi',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               type_=sa.Float(),
               existing_nullable=False)

    with op.batch_alter_table('property_facts', schema=None) as batch_op:
        batch_op.alter_column('property_type',
               existing_type=postgresql.ENUM('single_family', 'multi_family', 'commercial', name='property_type'),
               type_=sa.Enum('SINGLE_FAMILY', 'MULTI_FAMILY', 'COMMERCIAL', name='propertytype'),
               existing_nullable=False)
        batch_op.alter_column('bathrooms',
               existing_type=sa.NUMERIC(precision=3, scale=1),
               type_=sa.Float(),
               existing_nullable=False)
        batch_op.alter_column('construction_type',
               existing_type=postgresql.ENUM('frame', 'brick', 'masonry', name='construction_type'),
               type_=sa.Enum('FRAME', 'BRICK', 'MASONRY', name='constructiontype'),
               existing_nullable=False)
        batch_op.alter_column('last_sale_price',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               type_=sa.Float(),
               existing_nullable=True)
        batch_op.alter_column('assessed_value',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               type_=sa.Float(),
               existing_nullable=False)
        batch_op.alter_column('annual_taxes',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Float(),
               existing_nullable=False)
        batch_op.alter_column('interior_condition',
               existing_type=postgresql.ENUM('needs_gut', 'poor', 'average', 'new_reno', 'high_end', name='interior_condition'),
               type_=sa.Enum('NEEDS_GUT', 'POOR', 'AVERAGE', 'NEW_RENO', 'HIGH_END', name='interiorcondition'),
               existing_nullable=False)
        batch_op.alter_column('latitude',
               existing_type=sa.NUMERIC(precision=10, scale=8),
               type_=sa.Float(),
               existing_nullable=True)
        batch_op.alter_column('longitude',
               existing_type=sa.NUMERIC(precision=11, scale=8),
               type_=sa.Float(),
               existing_nullable=True)
        batch_op.alter_column('user_modified_fields',
               existing_type=postgresql.ARRAY(sa.TEXT()),
               type_=sa.JSON(),
               existing_nullable=True)
        batch_op.drop_index(batch_op.f('idx_property_facts_address'))
        batch_op.drop_index(batch_op.f('idx_property_facts_session_id'))
        batch_op.create_index(batch_op.f('ix_property_facts_address'), ['address'], unique=False)

    with op.batch_alter_table('ranked_comparables', schema=None) as batch_op:
        batch_op.alter_column('total_score',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               type_=sa.Float(),
               existing_nullable=False)
        batch_op.alter_column('recency_score',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               type_=sa.Float(),
               existing_nullable=False)
        batch_op.alter_column('proximity_score',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               type_=sa.Float(),
               existing_nullable=False)
        batch_op.alter_column('units_score',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               type_=sa.Float(),
               existing_nullable=False)
        batch_op.alter_column('beds_baths_score',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               type_=sa.Float(),
               existing_nullable=False)
        batch_op.alter_column('sqft_score',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               type_=sa.Float(),
               existing_nullable=False)
        batch_op.alter_column('construction_score',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               type_=sa.Float(),
               existing_nullable=False)
        batch_op.alter_column('interior_score',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               type_=sa.Float(),
               existing_nullable=False)
        batch_op.drop_index(batch_op.f('idx_ranked_comparables_session_id'))
        batch_op.create_index(batch_op.f('ix_ranked_comparables_session_id'), ['session_id'], unique=False)

    with op.batch_alter_table('scenarios', schema=None) as batch_op:
        batch_op.alter_column('scenario_type',
               existing_type=postgresql.ENUM('wholesale', 'fix_flip', 'buy_hold', name='scenario_type'),
               type_=sa.Enum('WHOLESALE', 'FIX_FLIP', 'BUY_HOLD', name='scenariotype'),
               existing_nullable=False)
        batch_op.alter_column('purchase_price',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               type_=sa.Float(),
               existing_nullable=False)
        batch_op.alter_column('summary',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=False)
        batch_op.drop_index(batch_op.f('idx_scenarios_session_id'))
        batch_op.create_index(batch_op.f('ix_scenarios_session_id'), ['session_id'], unique=False)

    with op.batch_alter_table('valuation_results', schema=None) as batch_op:
        batch_op.alter_column('conservative_arv',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               type_=sa.Float(),
               existing_nullable=False)
        batch_op.alter_column('likely_arv',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               type_=sa.Float(),
               existing_nullable=False)
        batch_op.alter_column('aggressive_arv',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               type_=sa.Float(),
               existing_nullable=False)
        batch_op.alter_column('all_valuations',
               existing_type=postgresql.ARRAY(sa.NUMERIC(precision=12, scale=2)),
               type_=sa.JSON(),
               nullable=False)
        batch_op.alter_column('key_drivers',
               existing_type=postgresql.ARRAY(sa.TEXT()),
               type_=sa.JSON(),
               existing_nullable=True)
        batch_op.drop_index(batch_op.f('idx_valuation_results_session_id'))
        batch_op.drop_constraint(batch_op.f('valuation_results_session_id_key'), type_='unique')
        batch_op.create_index(batch_op.f('ix_valuation_results_session_id'), ['session_id'], unique=True)

    with op.batch_alter_table('wholesale_scenarios', schema=None) as batch_op:
        batch_op.alter_column('mao',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               type_=sa.Float(),
               existing_nullable=False)
        batch_op.alter_column('contract_price',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               type_=sa.Float(),
               existing_nullable=False)
        batch_op.alter_column('assignment_fee_low',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               type_=sa.Float(),
               existing_nullable=False)
        batch_op.alter_column('assignment_fee_high',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               type_=sa.Float(),
               existing_nullable=False)
        batch_op.alter_column('estimated_repairs',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               type_=sa.Float(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wholesale_scenarios', schema=None) as batch_op:
        batch_op.alter_column('estimated_repairs',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=12, scale=2),
               existing_nullable=False)
        batch_op.alter_column('assignment_fee_high',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=12, scale=2),
               existing_nullable=False)
        batch_op.alter_column('assignment_fee_low',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=12, scale=2),
               existing_nullable=False)
        batch_op.alter_column('contract_price',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=12, scale=2),
               existing_nullable=False)
        batch_op.alter_column('mao',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=12, scale=2),
               existing_nullable=False)

    with op.batch_alter_table('valuation_results', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_valuation_results_session_id'))
        batch_op.create_unique_constraint(batch_op.f('valuation_results_session_id_key'), ['session_id'], postgresql_nulls_not_distinct=False)
        batch_op.create_index(batch_op.f('idx_valuation_results_session_id'), ['session_id'], unique=False)
        batch_op.alter_column('key_drivers',
               existing_type=sa.JSON(),
               type_=postgresql.ARRAY(sa.TEXT()),
               existing_nullable=True)
        batch_op.alter_column('all_valuations',
               existing_type=sa.JSON(),
               type_=postgresql.ARRAY(sa.NUMERIC(precision=12, scale=2)),
               nullable=True)
        batch_op.alter_column('aggressive_arv',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=12, scale=2),
               existing_nullable=False)
        batch_op.alter_column('likely_arv',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=12, scale=2),
               existing_nullable=False)
        batch_op.alter_column('conservative_arv',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=12, scale=2),
               existing_nullable=False)

    with op.batch_alter_table('scenarios', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_scenarios_session_id'))
        batch_op.create_index(batch_op.f('idx_scenarios_session_id'), ['session_id'], unique=False)
        batch_op.alter_column('summary',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False)
        batch_op.alter_column('purchase_price',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=12, scale=2),
               existing_nullable=False)
        batch_op.alter_column('scenario_type',
               existing_type=sa.Enum('WHOLESALE', 'FIX_FLIP', 'BUY_HOLD', name='scenariotype'),
               type_=postgresql.ENUM('wholesale', 'fix_flip', 'buy_hold', name='scenario_type'),
               existing_nullable=False)

    with op.batch_alter_table('ranked_comparables', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ranked_comparables_session_id'))
        batch_op.create_index(batch_op.f('idx_ranked_comparables_session_id'), ['session_id'], unique=False)
        batch_op.alter_column('interior_score',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=5, scale=2),
               existing_nullable=False)
        batch_op.alter_column('construction_score',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=5, scale=2),
               existing_nullable=False)
        batch_op.alter_column('sqft_score',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=5, scale=2),
               existing_nullable=False)
        batch_op.alter_column('beds_baths_score',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=5, scale=2),
               existing_nullable=False)
        batch_op.alter_column('units_score',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=5, scale=2),
               existing_nullable=False)
        batch_op.alter_column('proximity_score',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=5, scale=2),
               existing_nullable=False)
        batch_op.alter_column('recency_score',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=5, scale=2),
               existing_nullable=False)
        batch_op.alter_column('total_score',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=5, scale=2),
               existing_nullable=False)

    with op.batch_alter_table('property_facts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_property_facts_address'))
        batch_op.create_index(batch_op.f('idx_property_facts_session_id'), ['session_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_property_facts_address'), ['address'], unique=False)
        batch_op.alter_column('user_modified_fields',
               existing_type=sa.JSON(),
               type_=postgresql.ARRAY(sa.TEXT()),
               existing_nullable=True)
        batch_op.alter_column('longitude',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=11, scale=8),
               existing_nullable=True)
        batch_op.alter_column('latitude',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=10, scale=8),
               existing_nullable=True)
        batch_op.alter_column('interior_condition',
               existing_type=sa.Enum('NEEDS_GUT', 'POOR', 'AVERAGE', 'NEW_RENO', 'HIGH_END', name='interiorcondition'),
               type_=postgresql.ENUM('needs_gut', 'poor', 'average', 'new_reno', 'high_end', name='interior_condition'),
               existing_nullable=False)
        batch_op.alter_column('annual_taxes',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=False)
        batch_op.alter_column('assessed_value',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=12, scale=2),
               existing_nullable=False)
        batch_op.alter_column('last_sale_price',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=12, scale=2),
               existing_nullable=True)
        batch_op.alter_column('construction_type',
               existing_type=sa.Enum('FRAME', 'BRICK', 'MASONRY', name='constructiontype'),
               type_=postgresql.ENUM('frame', 'brick', 'masonry', name='construction_type'),
               existing_nullable=False)
        batch_op.alter_column('bathrooms',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=3, scale=1),
               existing_nullable=False)
        batch_op.alter_column('property_type',
               existing_type=sa.Enum('SINGLE_FAMILY', 'MULTI_FAMILY', 'COMMERCIAL', name='propertytype'),
               type_=postgresql.ENUM('single_family', 'multi_family', 'commercial', name='property_type'),
               existing_nullable=False)

    with op.batch_alter_table('fix_flip_scenarios', schema=None) as batch_op:
        batch_op.alter_column('roi',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=5, scale=2),
               existing_nullable=False)
        batch_op.alter_column('net_profit',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=12, scale=2),
               existing_nullable=False)
        batch_op.alter_column('exit_value',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=12, scale=2),
               existing_nullable=False)
        batch_op.alter_column('total_cost',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=12, scale=2),
               existing_nullable=False)
        batch_op.alter_column('closing_costs',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=12, scale=2),
               existing_nullable=False)
        batch_op.alter_column('financing_costs',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=12, scale=2),
               existing_nullable=False)
        batch_op.alter_column('holding_costs',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=12, scale=2),
               existing_nullable=False)
        batch_op.alter_column('renovation_cost',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=12, scale=2),
               existing_nullable=False)
        batch_op.alter_column('acquisition_cost',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=12, scale=2),
               existing_nullable=False)

    with op.batch_alter_table('comparable_valuations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_comparable_valuations_valuation_result_id'))
        batch_op.create_index(batch_op.f('idx_comparable_valuations_valuation_result_id'), ['valuation_result_id'], unique=False)
        batch_op.alter_column('adjustments',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
        batch_op.alter_column('adjusted_value',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=12, scale=2),
               existing_nullable=False)
        batch_op.alter_column('price_per_bedroom',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=12, scale=2),
               existing_nullable=False)
        batch_op.alter_column('price_per_unit',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=12, scale=2),
               existing_nullable=False)
        batch_op.alter_column('price_per_sqft',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=False)

    with op.batch_alter_table('comparable_sales', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_comparable_sales_session_id'))
        batch_op.drop_index(batch_op.f('ix_comparable_sales_address'))
        batch_op.create_index(batch_op.f('idx_comparable_sales_session_id'), ['session_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_comparable_sales_address'), ['address'], unique=False)
        batch_op.alter_column('longitude',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=11, scale=8),
               existing_nullable=True)
        batch_op.alter_column('latitude',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=10, scale=8),
               existing_nullable=True)
        batch_op.alter_column('distance_miles',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=5, scale=2),
               existing_nullable=False)
        batch_op.alter_column('interior_condition',
               existing_type=sa.Enum('NEEDS_GUT', 'POOR', 'AVERAGE', 'NEW_RENO', 'HIGH_END', name='interiorcondition'),
               type_=postgresql.ENUM('needs_gut', 'poor', 'average', 'new_reno', 'high_end', name='interior_condition'),
               existing_nullable=False)
        batch_op.alter_column('construction_type',
               existing_type=sa.Enum('FRAME', 'BRICK', 'MASONRY', name='constructiontype'),
               type_=postgresql.ENUM('frame', 'brick', 'masonry', name='construction_type'),
               existing_nullable=False)
        batch_op.alter_column('bathrooms',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=3, scale=1),
               existing_nullable=False)
        batch_op.alter_column('property_type',
               existing_type=sa.Enum('SINGLE_FAMILY', 'MULTI_FAMILY', 'COMMERCIAL', name='propertytype'),
               type_=postgresql.ENUM('single_family', 'multi_family', 'commercial', name='property_type'),
               existing_nullable=False)
        batch_op.alter_column('sale_price',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=12, scale=2),
               existing_nullable=False)

    with op.batch_alter_table('buy_hold_scenarios', schema=None) as batch_op:
        batch_op.alter_column('price_points',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False)
        batch_op.alter_column('capital_structures',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False)
        batch_op.alter_column('market_rent',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=False)

    with op.batch_alter_table('analysis_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_analysis_sessions_user_id'))
        batch_op.drop_index(batch_op.f('ix_analysis_sessions_session_id'))
        batch_op.create_index(batch_op.f('idx_analysis_sessions_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_analysis_sessions_session_id'), ['session_id'], unique=False)
        batch_op.create_unique_constraint(batch_op.f('analysis_sessions_session_id_key'), ['session_id'], postgresql_nulls_not_distinct=False)
        batch_op.alter_column('current_step',
               existing_type=sa.Enum('PROPERTY_FACTS', 'COMPARABLE_SEARCH', 'COMPARABLE_REVIEW', 'WEIGHTED_SCORING', 'VALUATION_MODELS', 'REPORT_GENERATION', name='workflowstep'),
               type_=postgresql.ENUM('PROPERTY_FACTS', 'COMPARABLE_SEARCH', 'COMPARABLE_REVIEW', 'WEIGHTED_SCORING', 'VALUATION_MODELS', 'REPORT_GENERATION', name='workflow_step'),
               existing_nullable=False,
               existing_server_default=sa.text("'PROPERTY_FACTS'::workflow_step"))

    # ### end Alembic commands ###
