"""baseline schema

Revision ID: 267725fe7017
Revises: 
Create Date: 2026-04-30 16:54:10.117775

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '267725fe7017'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # The baseline migration renames several PostgreSQL enum types from the
    # original names (e.g. 'workflow_step') to SQLAlchemy's auto-generated names
    # (e.g. 'workflowstep').  On a fresh database these target types don't exist
    # yet, so ALTER COLUMN ... TYPE <name> fails with "type does not exist".
    #
    # Create all target enum types here (IF NOT EXISTS so the migration stays
    # idempotent on databases where they were already created by SQLAlchemy).
    op.execute("""
        DO $$ BEGIN
            CREATE TYPE workflowstep AS ENUM (
                'PROPERTY_FACTS', 'COMPARABLE_SEARCH', 'COMPARABLE_REVIEW',
                'WEIGHTED_SCORING', 'VALUATION_MODELS', 'REPORT_GENERATION'
            );
        EXCEPTION WHEN duplicate_object THEN NULL;
        END $$;
    """)
    op.execute("""
        DO $$ BEGIN
            CREATE TYPE propertytype AS ENUM ('SINGLE_FAMILY', 'MULTI_FAMILY', 'COMMERCIAL');
        EXCEPTION WHEN duplicate_object THEN NULL;
        END $$;
    """)
    op.execute("""
        DO $$ BEGIN
            CREATE TYPE constructiontype AS ENUM ('FRAME', 'BRICK', 'MASONRY');
        EXCEPTION WHEN duplicate_object THEN NULL;
        END $$;
    """)
    op.execute("""
        DO $$ BEGIN
            CREATE TYPE interiorcondition AS ENUM (
                'NEEDS_GUT', 'POOR', 'AVERAGE', 'NEW_RENO', 'HIGH_END'
            );
        EXCEPTION WHEN duplicate_object THEN NULL;
        END $$;
    """)
    op.execute("""
        DO $$ BEGIN
            CREATE TYPE scenariotype AS ENUM ('WHOLESALE', 'FIX_FLIP', 'BUY_HOLD');
        EXCEPTION WHEN duplicate_object THEN NULL;
        END $$;
    """)

    # ### commands auto generated by Alembic - please adjust! ###

    # Enum column renames: use raw ALTER TABLE with USING cast.
    # batch_alter_table does not support postgresql_using, and PostgreSQL cannot
    # automatically cast between two differently-named enum types even if values match.
    # Pattern: col::text::newtype maps old values via text intermediary.
    #
    # analysis_sessions.current_step: workflow_step → workflowstep
    # Must drop the server_default first: PostgreSQL validates the default expression
    # against the new type before completing ALTER COLUMN TYPE, and
    # 'PROPERTY_FACTS'::workflow_step is invalid for the new workflowstep type.
    op.execute("ALTER TABLE analysis_sessions ALTER COLUMN current_step DROP DEFAULT")
    op.execute("""
        ALTER TABLE analysis_sessions
        ALTER COLUMN current_step TYPE workflowstep
        USING current_step::text::workflowstep
    """)
    op.execute("ALTER TABLE analysis_sessions ALTER COLUMN current_step SET DEFAULT 'PROPERTY_FACTS'::workflowstep")

    # comparable_sales enum renames
    op.execute("""
        ALTER TABLE comparable_sales
        ALTER COLUMN property_type TYPE propertytype
        USING upper(property_type::text)::propertytype
    """)
    op.execute("""
        ALTER TABLE comparable_sales
        ALTER COLUMN construction_type TYPE constructiontype
        USING upper(construction_type::text)::constructiontype
    """)
    op.execute("""
        ALTER TABLE comparable_sales
        ALTER COLUMN interior_condition TYPE interiorcondition
        USING upper(interior_condition::text)::interiorcondition
    """)

    # property_facts enum renames
    op.execute("""
        ALTER TABLE property_facts
        ALTER COLUMN property_type TYPE propertytype
        USING upper(property_type::text)::propertytype
    """)
    op.execute("""
        ALTER TABLE property_facts
        ALTER COLUMN construction_type TYPE constructiontype
        USING upper(construction_type::text)::constructiontype
    """)
    op.execute("""
        ALTER TABLE property_facts
        ALTER COLUMN interior_condition TYPE interiorcondition
        USING upper(interior_condition::text)::interiorcondition
    """)

    # scenarios.scenario_type: scenario_type → scenariotype
    op.execute("""
        ALTER TABLE scenarios
        ALTER COLUMN scenario_type TYPE scenariotype
        USING upper(scenario_type::text)::scenariotype
    """)

    with op.batch_alter_table('analysis_sessions', schema=None) as batch_op:
        # current_step already retyped above — only do index/constraint changes here
        batch_op.drop_constraint(batch_op.f('analysis_sessions_session_id_key'), type_='unique')
        batch_op.drop_index(batch_op.f('idx_analysis_sessions_session_id'))
        batch_op.drop_index(batch_op.f('idx_analysis_sessions_user_id'))
        batch_op.create_index(batch_op.f('ix_analysis_sessions_session_id'), ['session_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_analysis_sessions_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('buy_hold_scenarios', schema=None) as batch_op:
        batch_op.alter_column('market_rent',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Float(),
               existing_nullable=False)
        batch_op.alter_column('capital_structures',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=False)
        batch_op.alter_column('price_points',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=False)

    with op.batch_alter_table('comparable_sales', schema=None) as batch_op:
        batch_op.alter_column('sale_price',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               type_=sa.Float(),
               existing_nullable=False)
        # property_type, construction_type, interior_condition retyped above via raw SQL
        batch_op.alter_column('bathrooms',
               existing_type=sa.NUMERIC(precision=3, scale=1),
               type_=sa.Float(),
               existing_nullable=False)
        batch_op.alter_column('distance_miles',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               type_=sa.Float(),
               existing_nullable=False)
        batch_op.alter_column('latitude',
               existing_type=sa.NUMERIC(precision=10, scale=8),
               type_=sa.Float(),
               existing_nullable=True)
        batch_op.alter_column('longitude',
               existing_type=sa.NUMERIC(precision=11, scale=8),
               type_=sa.Float(),
               existing_nullable=True)
        batch_op.drop_index(batch_op.f('idx_comparable_sales_address'))
        batch_op.drop_index(batch_op.f('idx_comparable_sales_session_id'))
        batch_op.create_index(batch_op.f('ix_comparable_sales_address'), ['address'], unique=False)
        batch_op.create_index(batch_op.f('ix_comparable_sales_session_id'), ['session_id'], unique=False)

    with op.batch_alter_table('comparable_valuations', schema=None) as batch_op:
        batch_op.alter_column('price_per_sqft',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Float(),
               existing_nullable=False)
        batch_op.alter_column('price_per_unit',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               type_=sa.Float(),
               existing_nullable=False)
        batch_op.alter_column('price_per_bedroom',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               type_=sa.Float(),
               existing_nullable=False)
        batch_op.alter_column('adjusted_value',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               type_=sa.Float(),
               existing_nullable=False)
        batch_op.alter_column('adjustments',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
        batch_op.drop_index(batch_op.f('idx_comparable_valuations_valuation_result_id'))
        batch_op.create_index(batch_op.f('ix_comparable_valuations_valuation_result_id'), ['valuation_result_id'], unique=False)

    with op.batch_alter_table('fix_flip_scenarios', schema=None) as batch_op:
        batch_op.alter_column('acquisition_cost',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               type_=sa.Float(),
               existing_nullable=False)
        batch_op.alter_column('renovation_cost',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               type_=sa.Float(),
               existing_nullable=False)
        batch_op.alter_column('holding_costs',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               type_=sa.Float(),
               existing_nullable=False)
        batch_op.alter_column('financing_costs',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               type_=sa.Float(),
               existing_nullable=False)
        batch_op.alter_column('closing_costs',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               type_=sa.Float(),
               existing_nullable=False)
        batch_op.alter_column('total_cost',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               type_=sa.Float(),
               existing_nullable=False)
        batch_op.alter_column('exit_value',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               type_=sa.Float(),
               existing_nullable=False)
        batch_op.alter_column('net_profit',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               type_=sa.Float(),
               existing_nullable=False)
        batch_op.alter_column('roi',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               type_=sa.Float(),
               existing_nullable=False)

    with op.batch_alter_table('property_facts', schema=None) as batch_op:
        # property_type, construction_type, interior_condition retyped above via raw SQL
        batch_op.alter_column('bathrooms',
               existing_type=sa.NUMERIC(precision=3, scale=1),
               type_=sa.Float(),
               existing_nullable=False)
        batch_op.alter_column('last_sale_price',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               type_=sa.Float(),
               existing_nullable=True)
        batch_op.alter_column('assessed_value',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               type_=sa.Float(),
               existing_nullable=False)
        batch_op.alter_column('annual_taxes',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Float(),
               existing_nullable=False)
        # interior_condition retyped above via raw SQL
        batch_op.alter_column('latitude',
               existing_type=sa.NUMERIC(precision=10, scale=8),
               type_=sa.Float(),
               existing_nullable=True)
        batch_op.alter_column('longitude',
               existing_type=sa.NUMERIC(precision=11, scale=8),
               type_=sa.Float(),
               existing_nullable=True)
        batch_op.alter_column('user_modified_fields',
               existing_type=postgresql.ARRAY(sa.TEXT()),
               type_=sa.JSON(),
               existing_nullable=True)
        batch_op.drop_index(batch_op.f('idx_property_facts_address'))
        batch_op.drop_index(batch_op.f('idx_property_facts_session_id'))
        batch_op.create_index(batch_op.f('ix_property_facts_address'), ['address'], unique=False)

    with op.batch_alter_table('ranked_comparables', schema=None) as batch_op:
        batch_op.alter_column('total_score',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               type_=sa.Float(),
               existing_nullable=False)
        batch_op.alter_column('recency_score',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               type_=sa.Float(),
               existing_nullable=False)
        batch_op.alter_column('proximity_score',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               type_=sa.Float(),
               existing_nullable=False)
        batch_op.alter_column('units_score',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               type_=sa.Float(),
               existing_nullable=False)
        batch_op.alter_column('beds_baths_score',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               type_=sa.Float(),
               existing_nullable=False)
        batch_op.alter_column('sqft_score',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               type_=sa.Float(),
               existing_nullable=False)
        batch_op.alter_column('construction_score',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               type_=sa.Float(),
               existing_nullable=False)
        batch_op.alter_column('interior_score',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               type_=sa.Float(),
               existing_nullable=False)
        batch_op.drop_index(batch_op.f('idx_ranked_comparables_session_id'))
        batch_op.create_index(batch_op.f('ix_ranked_comparables_session_id'), ['session_id'], unique=False)

    with op.batch_alter_table('scenarios', schema=None) as batch_op:
        # scenario_type retyped above via raw SQL
        batch_op.alter_column('purchase_price',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               type_=sa.Float(),
               existing_nullable=False)
        batch_op.alter_column('summary',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=False)
        batch_op.drop_index(batch_op.f('idx_scenarios_session_id'))
        batch_op.create_index(batch_op.f('ix_scenarios_session_id'), ['session_id'], unique=False)

    with op.batch_alter_table('valuation_results', schema=None) as batch_op:
        batch_op.alter_column('conservative_arv',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               type_=sa.Float(),
               existing_nullable=False)
        batch_op.alter_column('likely_arv',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               type_=sa.Float(),
               existing_nullable=False)
        batch_op.alter_column('aggressive_arv',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               type_=sa.Float(),
               existing_nullable=False)
        batch_op.alter_column('all_valuations',
               existing_type=postgresql.ARRAY(sa.NUMERIC(precision=12, scale=2)),
               type_=sa.JSON(),
               nullable=False)
        batch_op.alter_column('key_drivers',
               existing_type=postgresql.ARRAY(sa.TEXT()),
               type_=sa.JSON(),
               existing_nullable=True)
        batch_op.drop_index(batch_op.f('idx_valuation_results_session_id'))
        batch_op.drop_constraint(batch_op.f('valuation_results_session_id_key'), type_='unique')
        batch_op.create_index(batch_op.f('ix_valuation_results_session_id'), ['session_id'], unique=True)

    with op.batch_alter_table('wholesale_scenarios', schema=None) as batch_op:
        batch_op.alter_column('mao',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               type_=sa.Float(),
               existing_nullable=False)
        batch_op.alter_column('contract_price',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               type_=sa.Float(),
               existing_nullable=False)
        batch_op.alter_column('assignment_fee_low',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               type_=sa.Float(),
               existing_nullable=False)
        batch_op.alter_column('assignment_fee_high',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               type_=sa.Float(),
               existing_nullable=False)
        batch_op.alter_column('estimated_repairs',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               type_=sa.Float(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wholesale_scenarios', schema=None) as batch_op:
        batch_op.alter_column('estimated_repairs',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=12, scale=2),
               existing_nullable=False)
        batch_op.alter_column('assignment_fee_high',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=12, scale=2),
               existing_nullable=False)
        batch_op.alter_column('assignment_fee_low',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=12, scale=2),
               existing_nullable=False)
        batch_op.alter_column('contract_price',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=12, scale=2),
               existing_nullable=False)
        batch_op.alter_column('mao',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=12, scale=2),
               existing_nullable=False)

    with op.batch_alter_table('valuation_results', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_valuation_results_session_id'))
        batch_op.create_unique_constraint(batch_op.f('valuation_results_session_id_key'), ['session_id'], postgresql_nulls_not_distinct=False)
        batch_op.create_index(batch_op.f('idx_valuation_results_session_id'), ['session_id'], unique=False)
        batch_op.alter_column('key_drivers',
               existing_type=sa.JSON(),
               type_=postgresql.ARRAY(sa.TEXT()),
               existing_nullable=True)
        batch_op.alter_column('all_valuations',
               existing_type=sa.JSON(),
               type_=postgresql.ARRAY(sa.NUMERIC(precision=12, scale=2)),
               nullable=True)
        batch_op.alter_column('aggressive_arv',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=12, scale=2),
               existing_nullable=False)
        batch_op.alter_column('likely_arv',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=12, scale=2),
               existing_nullable=False)
        batch_op.alter_column('conservative_arv',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=12, scale=2),
               existing_nullable=False)

    with op.batch_alter_table('scenarios', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_scenarios_session_id'))
        batch_op.create_index(batch_op.f('idx_scenarios_session_id'), ['session_id'], unique=False)
        batch_op.alter_column('summary',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False)
        batch_op.alter_column('purchase_price',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=12, scale=2),
               existing_nullable=False)
        batch_op.alter_column('scenario_type',
               existing_type=sa.Enum('WHOLESALE', 'FIX_FLIP', 'BUY_HOLD', name='scenariotype'),
               type_=postgresql.ENUM('wholesale', 'fix_flip', 'buy_hold', name='scenario_type'),
               existing_nullable=False)

    with op.batch_alter_table('ranked_comparables', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ranked_comparables_session_id'))
        batch_op.create_index(batch_op.f('idx_ranked_comparables_session_id'), ['session_id'], unique=False)
        batch_op.alter_column('interior_score',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=5, scale=2),
               existing_nullable=False)
        batch_op.alter_column('construction_score',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=5, scale=2),
               existing_nullable=False)
        batch_op.alter_column('sqft_score',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=5, scale=2),
               existing_nullable=False)
        batch_op.alter_column('beds_baths_score',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=5, scale=2),
               existing_nullable=False)
        batch_op.alter_column('units_score',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=5, scale=2),
               existing_nullable=False)
        batch_op.alter_column('proximity_score',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=5, scale=2),
               existing_nullable=False)
        batch_op.alter_column('recency_score',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=5, scale=2),
               existing_nullable=False)
        batch_op.alter_column('total_score',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=5, scale=2),
               existing_nullable=False)

    with op.batch_alter_table('property_facts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_property_facts_address'))
        batch_op.create_index(batch_op.f('idx_property_facts_session_id'), ['session_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_property_facts_address'), ['address'], unique=False)
        batch_op.alter_column('user_modified_fields',
               existing_type=sa.JSON(),
               type_=postgresql.ARRAY(sa.TEXT()),
               existing_nullable=True)
        batch_op.alter_column('longitude',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=11, scale=8),
               existing_nullable=True)
        batch_op.alter_column('latitude',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=10, scale=8),
               existing_nullable=True)
        batch_op.alter_column('interior_condition',
               existing_type=sa.Enum('NEEDS_GUT', 'POOR', 'AVERAGE', 'NEW_RENO', 'HIGH_END', name='interiorcondition'),
               type_=postgresql.ENUM('needs_gut', 'poor', 'average', 'new_reno', 'high_end', name='interior_condition'),
               existing_nullable=False)
        batch_op.alter_column('annual_taxes',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=False)
        batch_op.alter_column('assessed_value',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=12, scale=2),
               existing_nullable=False)
        batch_op.alter_column('last_sale_price',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=12, scale=2),
               existing_nullable=True)
        batch_op.alter_column('construction_type',
               existing_type=sa.Enum('FRAME', 'BRICK', 'MASONRY', name='constructiontype'),
               type_=postgresql.ENUM('frame', 'brick', 'masonry', name='construction_type'),
               existing_nullable=False)
        batch_op.alter_column('bathrooms',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=3, scale=1),
               existing_nullable=False)
        batch_op.alter_column('property_type',
               existing_type=sa.Enum('SINGLE_FAMILY', 'MULTI_FAMILY', 'COMMERCIAL', name='propertytype'),
               type_=postgresql.ENUM('single_family', 'multi_family', 'commercial', name='property_type'),
               existing_nullable=False)

    with op.batch_alter_table('fix_flip_scenarios', schema=None) as batch_op:
        batch_op.alter_column('roi',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=5, scale=2),
               existing_nullable=False)
        batch_op.alter_column('net_profit',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=12, scale=2),
               existing_nullable=False)
        batch_op.alter_column('exit_value',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=12, scale=2),
               existing_nullable=False)
        batch_op.alter_column('total_cost',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=12, scale=2),
               existing_nullable=False)
        batch_op.alter_column('closing_costs',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=12, scale=2),
               existing_nullable=False)
        batch_op.alter_column('financing_costs',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=12, scale=2),
               existing_nullable=False)
        batch_op.alter_column('holding_costs',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=12, scale=2),
               existing_nullable=False)
        batch_op.alter_column('renovation_cost',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=12, scale=2),
               existing_nullable=False)
        batch_op.alter_column('acquisition_cost',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=12, scale=2),
               existing_nullable=False)

    with op.batch_alter_table('comparable_valuations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_comparable_valuations_valuation_result_id'))
        batch_op.create_index(batch_op.f('idx_comparable_valuations_valuation_result_id'), ['valuation_result_id'], unique=False)
        batch_op.alter_column('adjustments',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
        batch_op.alter_column('adjusted_value',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=12, scale=2),
               existing_nullable=False)
        batch_op.alter_column('price_per_bedroom',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=12, scale=2),
               existing_nullable=False)
        batch_op.alter_column('price_per_unit',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=12, scale=2),
               existing_nullable=False)
        batch_op.alter_column('price_per_sqft',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=False)

    with op.batch_alter_table('comparable_sales', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_comparable_sales_session_id'))
        batch_op.drop_index(batch_op.f('ix_comparable_sales_address'))
        batch_op.create_index(batch_op.f('idx_comparable_sales_session_id'), ['session_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_comparable_sales_address'), ['address'], unique=False)
        batch_op.alter_column('longitude',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=11, scale=8),
               existing_nullable=True)
        batch_op.alter_column('latitude',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=10, scale=8),
               existing_nullable=True)
        batch_op.alter_column('distance_miles',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=5, scale=2),
               existing_nullable=False)
        batch_op.alter_column('interior_condition',
               existing_type=sa.Enum('NEEDS_GUT', 'POOR', 'AVERAGE', 'NEW_RENO', 'HIGH_END', name='interiorcondition'),
               type_=postgresql.ENUM('needs_gut', 'poor', 'average', 'new_reno', 'high_end', name='interior_condition'),
               existing_nullable=False)
        batch_op.alter_column('construction_type',
               existing_type=sa.Enum('FRAME', 'BRICK', 'MASONRY', name='constructiontype'),
               type_=postgresql.ENUM('frame', 'brick', 'masonry', name='construction_type'),
               existing_nullable=False)
        batch_op.alter_column('bathrooms',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=3, scale=1),
               existing_nullable=False)
        batch_op.alter_column('property_type',
               existing_type=sa.Enum('SINGLE_FAMILY', 'MULTI_FAMILY', 'COMMERCIAL', name='propertytype'),
               type_=postgresql.ENUM('single_family', 'multi_family', 'commercial', name='property_type'),
               existing_nullable=False)
        batch_op.alter_column('sale_price',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=12, scale=2),
               existing_nullable=False)

    with op.batch_alter_table('buy_hold_scenarios', schema=None) as batch_op:
        batch_op.alter_column('price_points',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False)
        batch_op.alter_column('capital_structures',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False)
        batch_op.alter_column('market_rent',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=False)

    with op.batch_alter_table('analysis_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_analysis_sessions_user_id'))
        batch_op.drop_index(batch_op.f('ix_analysis_sessions_session_id'))
        batch_op.create_index(batch_op.f('idx_analysis_sessions_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_analysis_sessions_session_id'), ['session_id'], unique=False)
        batch_op.create_unique_constraint(batch_op.f('analysis_sessions_session_id_key'), ['session_id'], postgresql_nulls_not_distinct=False)
        batch_op.alter_column('current_step',
               existing_type=sa.Enum('PROPERTY_FACTS', 'COMPARABLE_SEARCH', 'COMPARABLE_REVIEW', 'WEIGHTED_SCORING', 'VALUATION_MODELS', 'REPORT_GENERATION', name='workflowstep'),
               type_=postgresql.ENUM('PROPERTY_FACTS', 'COMPARABLE_SEARCH', 'COMPARABLE_REVIEW', 'WEIGHTED_SCORING', 'VALUATION_MODELS', 'REPORT_GENERATION', name='workflow_step'),
               existing_nullable=False,
               existing_server_default=sa.text("'PROPERTY_FACTS'::workflow_step"))

    # ### end Alembic commands ###
