"""Add Pipeline Stage Config model (manual)

Revision ID: 5f9bc65a48ea
Revises: q7r8s9t0u1v2
Create Date: 2026-05-23 14:17:55.795736

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f9bc65a48ea'
down_revision = 'q7r8s9t0u1v2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'pipeline_stage_configs',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('stage_name', sa.String(length=255), nullable=False),
        sa.Column('order', sa.Integer(), nullable=False),
        sa.Column('weight', sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('order'),
        sa.UniqueConstraint('stage_name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pipeline_stage_configs')
    # ### end Alembic commands ###
