#!/usr/bin/env bash
# =============================================================================
# 07-create-env-file.sh
# VPS Setup — Task 3.1: Write /home/deploy/app/backend/.env with all required
#             production variables.
#
# Requirements: 3.4, 3.8, 7.1, 7.2, 7.3
#
# Run as the deploy user on the Hetzner CX22 VPS (Ubuntu 22.04 LTS):
#   bash 07-create-env-file.sh
#
# Required environment variable:
#   APP_USER_PASSWORD   — password for the app_user PostgreSQL role
#                         (set by 05-postgres-setup.sh)
#
# Optional flags:
#   --force             — overwrite an existing .env file
#
# This script is IDEMPOTENT — it will NOT overwrite an existing .env unless
# --force is passed.
# =============================================================================

set -euo pipefail

# ── Colour helpers ────────────────────────────────────────────────────────────
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
CYAN='\033[0;36m'
NC='\033[0m' # No Colour

info()  { echo -e "${GREEN}[INFO]${NC}  $*"; }
warn()  { echo -e "${YELLOW}[WARN]${NC}  $*"; }
error() { echo -e "${RED}[ERROR]${NC} $*" >&2; }
die()   { error "$*"; exit 1; }

# ── Parse flags ───────────────────────────────────────────────────────────────
FORCE=false
for arg in "$@"; do
    case "$arg" in
        --force) FORCE=true ;;
        *) die "Unknown argument: $arg. Usage: bash $0 [--force]" ;;
    esac
done

# ── Paths ─────────────────────────────────────────────────────────────────────
APP_DIR="/home/deploy/app"
ENV_EXAMPLE="${APP_DIR}/backend/.env.example"
ENV_FILE="${APP_DIR}/backend/.env"

# ── Verify we are the deploy user ─────────────────────────────────────────────
if [[ "$(whoami)" != "deploy" ]]; then
    die "This script must be run as the 'deploy' user. Current user: $(whoami)"
fi

# ── Verify .env.example exists ────────────────────────────────────────────────
if [[ ! -f "$ENV_EXAMPLE" ]]; then
    die ".env.example not found at $ENV_EXAMPLE. Has the repo been cloned? (run 04-clone-repo.sh first)"
fi

# ── Idempotency check ─────────────────────────────────────────────────────────
if [[ -f "$ENV_FILE" ]] && [[ "$FORCE" == "false" ]]; then
    warn ".env already exists at $ENV_FILE"
    warn "Skipping creation. Pass --force to overwrite."
    echo ""
    echo "  To force recreation:  bash $0 --force"
    echo "  To view current file: cat $ENV_FILE  (mode 600 — requires deploy user)"
    echo ""
    exit 0
fi

if [[ -f "$ENV_FILE" ]] && [[ "$FORCE" == "true" ]]; then
    warn "--force flag set. Backing up existing .env before overwriting..."
    cp "$ENV_FILE" "${ENV_FILE}.bak.$(date +%Y%m%d%H%M%S)"
    info "  Backup saved to ${ENV_FILE}.bak.*"
fi

# ── Resolve APP_USER_PASSWORD ─────────────────────────────────────────────────
if [[ -z "${APP_USER_PASSWORD:-}" ]]; then
    echo ""
    warn "APP_USER_PASSWORD environment variable is not set."
    echo -n "  Enter the app_user PostgreSQL password (set during 05-postgres-setup.sh): "
    read -rs APP_USER_PASSWORD
    echo ""
    if [[ -z "$APP_USER_PASSWORD" ]]; then
        die "Password cannot be empty. Aborting."
    fi
fi

# ── Generate cryptographic secrets ────────────────────────────────────────────
info "Generating SECRET_KEY (64-char hex)..."
SECRET_KEY=$(python3 -c "import secrets; print(secrets.token_hex(32))")
if [[ ${#SECRET_KEY} -ne 64 ]]; then
    die "SECRET_KEY generation failed — expected 64 chars, got ${#SECRET_KEY}"
fi
info "  ✓ SECRET_KEY generated."

info "Generating JWT_SECRET_KEY (64-char hex)..."
JWT_SECRET_KEY=$(python3 -c "import secrets; print(secrets.token_hex(32))")
if [[ ${#JWT_SECRET_KEY} -ne 64 ]]; then
    die "JWT_SECRET_KEY generation failed — expected 64 chars, got ${#JWT_SECRET_KEY}"
fi
info "  ✓ JWT_SECRET_KEY generated."

# ── Write the .env file ───────────────────────────────────────────────────────
info "Writing $ENV_FILE ..."

cat > "$ENV_FILE" <<ENV
# =============================================================================
# /home/deploy/app/backend/.env  — PRODUCTION
# Generated by 07-create-env-file.sh on $(date -u +"%Y-%m-%dT%H:%M:%SZ")
#
# SECURITY: This file is mode 600 (readable only by the deploy user).
#           NEVER commit this file to git.
# =============================================================================

# ── Database ──────────────────────────────────────────────────────────────────
# Local PostgreSQL — no sslmode needed for loopback connections
DATABASE_URL=postgresql://app_user:${APP_USER_PASSWORD}@localhost:5432/real_estate_analysis

# ── Flask ─────────────────────────────────────────────────────────────────────
SECRET_KEY=${SECRET_KEY}
JWT_SECRET_KEY=${JWT_SECRET_KEY}
FLASK_ENV=production

# ── Async processing ──────────────────────────────────────────────────────────
# Celery is excluded from the initial deployment.
# Set to false to run comparable search synchronously.
USE_ASYNC_COMPARABLE_SEARCH=false

# Redis URLs are set to prevent startup warnings even though Celery is disabled.
REDIS_URL=redis://localhost:6379/0
CELERY_BROKER_URL=redis://localhost:6379/0
CELERY_RESULT_BACKEND=redis://localhost:6379/0

# ── External API keys — FILL THESE IN MANUALLY ────────────────────────────────
GOOGLE_MAPS_API_KEY=REPLACE_ME
GOOGLE_AI_API_KEY=REPLACE_ME
RENTCAST_API_KEY=REPLACE_ME
MLS_API_KEY=REPLACE_ME
TAX_ASSESSOR_API_KEY=REPLACE_ME
CHICAGO_DATA_API_KEY=REPLACE_ME
COOK_COUNTY_APP_TOKEN=REPLACE_ME
SOCRATA_APP_TOKEN=REPLACE_ME

# ── HubSpot ───────────────────────────────────────────────────────────────────
# Generate a Fernet key with:
#   python3 -c "from cryptography.fernet import Fernet; print(Fernet.generate_key().decode())"
HUBSPOT_ENCRYPTION_KEY=REPLACE_ME
HUBSPOT_CLIENT_SECRET=REPLACE_ME
HUBSPOT_ENGAGEMENT_SYNC_INTERVAL_MINUTES=60

# ── Google Sheets ─────────────────────────────────────────────────────────────
GOOGLE_SHEETS_CREDENTIALS_FILE=/home/deploy/app/backend/credentials.json
ENV

info "  ✓ $ENV_FILE written."

# ── Set permissions ───────────────────────────────────────────────────────────
info "Setting file permissions to 600 (owner read/write only)..."
chmod 600 "$ENV_FILE"
info "  ✓ chmod 600 applied."

# Ownership should already be deploy:deploy since we're running as deploy,
# but make it explicit in case the file was created with a different umask.
chown deploy:deploy "$ENV_FILE"
info "  ✓ Ownership set to deploy:deploy."

# ── Verify permissions ────────────────────────────────────────────────────────
info "Verifying file permissions..."
PERMS=$(stat -c "%a %U:%G" "$ENV_FILE")
if [[ "$PERMS" == "600 deploy:deploy" ]]; then
    info "  ✓ Permissions verified: $PERMS"
else
    die "  Permission check failed. Expected '600 deploy:deploy', got '$PERMS'"
fi

# ── Verify required keys are present ─────────────────────────────────────────
info "Verifying required variables are present in .env..."

REQUIRED_VARS=(
    "DATABASE_URL"
    "SECRET_KEY"
    "JWT_SECRET_KEY"
    "FLASK_ENV"
    "USE_ASYNC_COMPARABLE_SEARCH"
    "REDIS_URL"
    "CELERY_BROKER_URL"
)

ALL_PRESENT=true
for var in "${REQUIRED_VARS[@]}"; do
    if grep -q "^${var}=" "$ENV_FILE"; then
        info "  ✓ $var"
    else
        error "  ✗ $var is MISSING from $ENV_FILE"
        ALL_PRESENT=false
    fi
done

if [[ "$ALL_PRESENT" != "true" ]]; then
    die "One or more required variables are missing. Check $ENV_FILE manually."
fi

# ── Verify SECRET_KEY is not the dev default ──────────────────────────────────
info "Verifying SECRET_KEY is not the development default..."
if grep -q "^SECRET_KEY=your-secret-key-here" "$ENV_FILE" || \
   grep -q "^SECRET_KEY=dev-secret-key" "$ENV_FILE"; then
    die "SECRET_KEY is still set to a development default. This will cause Flask to refuse to start in production."
fi
info "  ✓ SECRET_KEY is not a known development default."

# ── Verify key lengths ────────────────────────────────────────────────────────
info "Verifying SECRET_KEY and JWT_SECRET_KEY are 64 characters..."

STORED_SECRET=$(grep "^SECRET_KEY=" "$ENV_FILE" | cut -d'=' -f2)
STORED_JWT=$(grep "^JWT_SECRET_KEY=" "$ENV_FILE" | cut -d'=' -f2)

if [[ ${#STORED_SECRET} -ne 64 ]]; then
    die "SECRET_KEY in .env is ${#STORED_SECRET} chars, expected 64."
fi
info "  ✓ SECRET_KEY is 64 characters."

if [[ ${#STORED_JWT} -ne 64 ]]; then
    die "JWT_SECRET_KEY in .env is ${#STORED_JWT} chars, expected 64."
fi
info "  ✓ JWT_SECRET_KEY is 64 characters."

# =============================================================================
# Summary and manual checklist
# =============================================================================
echo ""
echo "============================================================"
echo "  Task 3.1 complete — production .env file created"
echo "============================================================"
echo ""
echo "  File:        $ENV_FILE"
echo "  Permissions: 600 (deploy:deploy)"
echo "  DATABASE_URL: postgresql://app_user:***@localhost:5432/real_estate_analysis"
echo "  SECRET_KEY:   [64-char hex — generated]"
echo "  JWT_SECRET_KEY: [64-char hex — generated]"
echo "  FLASK_ENV:    production"
echo "  USE_ASYNC_COMPARABLE_SEARCH: false"
echo ""
echo -e "${YELLOW}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo -e "${YELLOW}  ⚠  MANUAL ACTION REQUIRED — fill in these API keys:${NC}"
echo -e "${YELLOW}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo ""
echo -e "  ${CYAN}Edit the file:${NC}  nano $ENV_FILE"
echo ""
echo "  Keys to fill in (currently set to REPLACE_ME):"
echo ""
echo "  [ ] GOOGLE_MAPS_API_KEY      — Google Maps Platform console"
echo "  [ ] GOOGLE_AI_API_KEY        — Google AI Studio / Vertex AI"
echo "  [ ] RENTCAST_API_KEY         — https://developers.rentcast.io"
echo "  [ ] MLS_API_KEY              — MLS data provider"
echo "  [ ] TAX_ASSESSOR_API_KEY     — Tax assessor data provider"
echo "  [ ] CHICAGO_DATA_API_KEY     — Chicago open data portal"
echo "  [ ] COOK_COUNTY_APP_TOKEN    — https://data.cookcountyil.gov/profile/app_tokens"
echo "  [ ] SOCRATA_APP_TOKEN        — Socrata open data"
echo "  [ ] HUBSPOT_ENCRYPTION_KEY   — Fernet key (see comment in .env for generation command)"
echo "  [ ] HUBSPOT_CLIENT_SECRET    — HubSpot app settings"
echo ""
echo "  Optional:"
echo "  [ ] GOOGLE_SHEETS_CREDENTIALS_FILE — upload credentials.json to /home/deploy/app/backend/"
echo ""
echo -e "${YELLOW}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo ""
echo "  NEXT STEP: After filling in all API keys, proceed to"
echo "  08-gunicorn-service.sh (Task 4.1) to install the systemd service."
echo ""
echo "============================================================"
