#!/usr/bin/env python3
"""Write capture-data-snapshot.sh with correct content for B-B repo."""
import os
import stat

L = []

# Line by line construction - each element is an exact line (no trailing newline)

L.append("#!/usr/bin/env bash")
L.append("# ===========================================================================")
L.append("# capture-data-snapshot.sh — Capture DB Metrics Snapshot After pg_restore")
L.append("# ===========================================================================")
L.append("# Captures key database metrics to backend/data-snapshot.json so that")
L.append("# verify-data-snapshot.sh can later detect regressions.")
L.append("#")
L.append("# Usage:")
L.append("#   ./scripts/capture-data-snapshot.sh")
L.append("#   ./scripts/capture-data-snapshot.sh --db-url postgresql://user:***@host:port/db")
L.append("#")
L.append("# Environment:")
L.append("#   DATABASE_URL  — PostgreSQL connection string")
L.append("#                   (default: postgresql://jeffreyops@localhost:***@gmail.com'")
L.append("#   user_ids       — list of {id, email, display_name} from the users table")
L.append("#   checked_at     — UTC timestamp of capture")
L.append("# ===========================================================================")
L.append("")
L.append("set -euo pipefail")
L.append("")
L.append("# Parse --db-url argument")
L.append('if [[ "${1:-}" == "--db-url" ]]; then')
L.append("    shift")
L.append('    DATABASE_URL="${1:-}"')
L.append("    shift || true")
L.append("fi")
L.append("")
L.append("# Resolve paths")
L.append('SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"')
L.append('PROJECT_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"')
L.append('SNAPSHOT_FILE="${SNAPSHOT_FILE:-${PROJECT_ROOT}/backend/data-snapshot.json}"')
L.append("")
L.append("# Database connection")
L.append("DEFAULT_DB_URL=\"postgresql://jeffreyops@localhost:5433/real_estate_analysis\"")
L.append('DATABASE_URL="${DATABASE_URL:-$DEFAULT_DB_URL}"')
L.append("")
L.append("# Load DATABASE_URL from ../backend/.env if not already set and file exists")
L.append('if [[ "$DATABASE_URL" == "$DEFAULT_DB_URL" ]]; then')
L.append('    ENV_FILE="${PROJECT_ROOT}/backend/.env"')
L.append('    if [[ -f "$ENV_FILE" ]]; then')
L.append("        # shellcheck source=/dev/null")
L.append('        source "$ENV_FILE"')
L.append('        DATABASE_URL="${DATABASE_URL:-$DEFAULT_DB_URL}"')
L.append("    fi")
L.append("fi")
L.append("")
L.append('PG_USER=""')
L.append('PG_PASS=""')
L.append('PG_HOST=""')
L.append('PG_PORT=""')
L.append('PG_DB=""')
L.append("")
L.append("# Parse postgresql://user[:pass]@host:port/dbname")
L.append('if [[ "$DATABASE_URL" =~ ^postgresql://([^:@]+)(:([^@]*))?@([^:]+):([0-9]+)/(.+)$ ]]; then')
L.append('    PG_USER="${BASH_REMATCH[1]}"')
L.append('    PG_PASS="${BASH_REMATCH[3]:-}"')
L.append('    PG_HOST="${BASH_REMATCH[4]}"')
L.append('    PG_PORT="${BASH_REMATCH[5]}"')
L.append('    PG_DB="${BASH_REMATCH[6]}"')
L.append("else")
L.append('    echo "[ERROR] Could not parse DATABASE_URL: $DATABASE_URL" >&2')
L.append('    echo "  Expected format: postgresql://user[:pass]@host:port/dbname" >&2')
L.append("    exit 1")
L.append("fi")
L.append("")
L.append('PSQL_ARGS=(-h "$PG_HOST" -p "$PG_PORT" -d "$PG_DB" -U "$PG_USER" -t -A)')
L.append("")
L.append("# Export password if present (psql reads PGPASSWORD env var)")
L.append('if [[ -n "$PG_PASS" ]]; then')
L.append('    export PGPASSWORD="$PG_PASS"')
L.append("fi")
L.append("")
L.append("# Helper: run a single-value SQL query")
L.append("psql_value() {")
L.append('    psql "${PSQL_ARGS[@]}" -c "$1" 2>/dev/null | head -1 | tr -d "[:space:]" || echo "null"')
L.append("}")
L.append("")
L.append("# Check psql availability")
L.append("if ! command -v psql &>/dev/null; then")
L.append('    echo "[ERROR] psql is not installed or not in PATH" >&2')
L.append("    exit 1")
L.append("fi")
L.append("")
L.append("# Test database connectivity")
L.append('echo "[capture-data-snapshot] Testing database connection..."')
L.append('if ! psql "${PSQL_ARGS[@]}" -c "SELECT 1;" >/dev/null 2>/dev/null; then')
L.append('    echo "[ERROR] Cannot connect to PostgreSQL at ${PG_HOST}:${PG_PORT}/${PG_DB} as ${PG_USER}" >&2')
L.append("    exit 1")
L.append("fi")
L.append('echo "[capture-data-snapshot] Connection OK"')
L.append("")
L.append("# Capture metrics")
L.append('echo "[capture-data-snapshot] Capturing metrics..."')
L.append("")
L.append('LEAD_COUNT=$(psql_value "SELECT COUNT(*) FROM leads;")')
L.append('USER_COUNT=$(psql_value "SELECT COUNT(*) FROM users;")')
L.append("CHECKED_AT=$(psql_value \"SELECT TO_CHAR(NOW() AT TIME ZONE 'UTC', 'YYYY-MM-DD\\\"T\\\"HH24:MI:SS\\\"Z\\\"');\")")
L.append("")
L.append("# Get ben's user_id from the users table by email")
L.append("BEN_USER_ID=$(psql_value \"SELECT user_id FROM users WHERE email = 'ben.d.staples.7@gmail.com' LIMIT 1;\")")
L.append('if [[ "$BEN_USER_ID" == "null" ]] || [[ -z "$BEN_USER_ID" ]]; then')
L.append('    BEN_LEAD_COUNT="0"')
L.append("    echo \"[capture-data-snapshot] WARNING: No user found with email 'ben.d.staples.7@gmail.com' — ben_lead_count set to 0\" >&2")
L.append("else")
L.append("    BEN_LEAD_COUNT=$(psql_value \"SELECT COUNT(*) FROM leads WHERE owner_user_id = '${BEN_USER_ID}';\")")
L.append("fi")
L.append("")
L.append("# Get all users as a JSON array of {id, email, display_name} objects")
L.append('USER_IDS_JSON="[]"')
L.append("USER_IDS_RAW=$(psql \"${PSQL_ARGS[@]}\" -c \"")
L.append("    SELECT json_agg(")
L.append("        json_build_object(")
L.append("            'id', user_id,")
L.append("            'email', email,")
L.append("            'display_name', display_name")
L.append("        ) ORDER BY id")
L.append("    ) FROM users;")
L.append('" 2>/dev/null | head -1 | tr -d "[:space:]")')
L.append("")
L.append('if [[ -n "$USER_IDS_RAW" ]] && [[ "$USER_IDS_RAW" != "null" ]]; then')
L.append('    USER_IDS_JSON="$USER_IDS_RAW"')
L.append("fi")
L.append("")
L.append("# Write snapshot JSON")
L.append('echo "[capture-data-snapshot] Writing snapshot to ${SNAPSHOT_FILE}..."')
L.append("")
L.append('mkdir -p "$(dirname "$SNAPSHOT_FILE")"')
L.append("")
L.append('cat > "$SNAPSHOT_FILE" <<SNAPSHOT_EOF')
L.append("{")
L.append("  \"lead_count\": ${LEAD_COUNT},")
L.append("  \"user_count\": ${USER_COUNT},")
L.append("  \"ben_lead_count\": ${BEN_LEAD_COUNT},")
L.append("  \"user_ids\": ${USER_IDS_JSON},")
L.append('  "checked_at": "${CHECKED_AT}"')
L.append("}")
L.append("SNAPSHOT_EOF")
L.append("")
L.append('echo "[capture-data-snapshot] Snapshot saved to ${SNAPSHOT_FILE}"')
L.append('echo "[capture-data-snapshot]   lead_count:     ${LEAD_COUNT}"')
L.append('echo "[capture-data-snapshot]   user_count:     ${USER_COUNT}"')
L.append('echo "[capture-data-snapshot]   ben_lead_count: ${BEN_LEAD_COUNT}"')
L.append('echo "[capture-data-snapshot]   checked_at:     ${CHECKED_AT}"')
L.append('echo "[capture-data-snapshot] Done"')

path = '/home/jeffreyops/B-B-Commercial-RE-Underwriting/scripts/capture-data-snapshot.sh'
content = '\n'.join(L) + '\n'
with open(path, 'w') as f:
    f.write(content)
os.chmod(path, stat.S_IRWXU | stat.S_IRGRP | stat.S_IXGRP | stat.S_IROTH | stat.S_IXOTH)
print(f'Written {len(L)} lines to {path}')
